// common
import './common/footer.html';
import './common/layout-pages.html';
import './common/layout.horizontal.html';
import './common/layout.html';
import './common/layout.js';
import './common/offsidebar.html';
import './common/offsidebar.js';
import './common/sidebar.html';
import './common/sidebar.js';
import './common/topnavbar.horizontal.html';
import './common/topnavbar.html';
import './common/topnavbar.js';
// Dashboard
import './views/dashboard.html';
import './views/dashboard.js';
// Processes
import './views/processes.html';
import './views/processes.js';
// Process
import './views/process.html';
import './views/process.js';
// Scenario
import './views/scenario.html';
import './views/scenario.js';
// Activities
import './views/activity.html';
import './views/activity.js';
// Subactivities
import './views/subactivity.html';
import './views/subactivity.js';
// Modal
import './common/modal.html';
import './common/modal.js';
